Q_source_total: 8760 # from Clayton paper, max possible. # 620 is 10x katey anecdodal # 62 is from katey in meeting  # g/m^2/year 10x to get ground level conc. to match
source_area: 600  # m^2

n_source_x: 1 #10
n_source_y: 1 #10
span_source_x: [0,0] #[-5, 5]
span_source_y: [0,0] #[-5, 5]

source_loc_y: 2500
source_loc_x: 0
source_loc_z: 0 # Keep zero

n_retro_x: 30
n_retro_y: 10
n_retro_z: 5

span_retro_x: [-5, 100]
span_retro_y: [-25, 25]
span_retro_z: [0, 3]

retro_loc_x : 0
retro_loc_y : 2500
